title: 古文观止
author: 
  name: Mengzi
description: 传承中华文化，发扬民族智慧
baseurl: "/enigma" # the subpath of your site, e.g. /blog
url: "mapxn.github.io" # the base hostname & protocol for your site, e.g. http://example.com
lang: zh

# Build settings
theme: minima
paginate: 5

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%Y年%m月%d日"

# permalink: /:year:month:day/:title.html
plugins:
  - jekyll-feed
  - jekyll-paginate