name: GitHub Actions Demo
on:
  watch:
    types: [started]
  schedule:
    - cron:  '0 8 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: PrepareJsonPackage
        id: step_one
        run: |
           git config --global user.name "mapxn"
           git config --global user.email "${{ secrets.EMAIL }}"
           wget https://github.com/mapxn/enigma/releases/download/v0.0.1/mock.jar
           echo "FILENAME=$(java -jar mock.jar)" >> $GITHUB_ENV
           git clone https://github.com/mapxn/enigma.git
           cd enigma
           git checkout gh-pages
           mv ../${{ env.FILENAME }} ./
           echo "- [${{ env.FILENAME }}](./${{ env.FILENAME }})" >> README.md
           git add -A
           git commit -m "Update engima"
           git push https://mapxn:${GITHUB_TOKEN}@github.com/mapxn/enigma.git gh-pages
