name: GitHub Actions Demo
on:
  watch:
    types: [started]
  schedule:
    - cron:  '0 8 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: PrepareDate
        id: step_one
        run: |
           wget https://github.com/mapxn/enigma/releases/download/v0.0.1/mockV2.jar
           echo "FILENAME=$(java -jar mockV2.jar)" >> $GITHUB_ENV
      - name: CommitFile
        id: step_two
        run: |
           git config --global user.name "mapxn"
           git config --global user.email "${{ secrets.EMAIL }}"
           git clone https://github.com/mapxn/enigma.git
           cd enigma
           git checkout gh-pages
           mv ../${{ env.FILENAME }}.md ./
           echo "- [${{ env.FILENAME }}](./${{ env.FILENAME }})" >> README.md
           git add -A
           git commit -m "Update engima"
           git push https://mapxn:${{ secrets.GITHUB_TOKEN }}@github.com/mapxn/enigma.git gh-pages
