name: GitHub Actions Demo
on:
  schedule:
    - cron:  '0 20 * * *'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: PrepareDate
        id: step_one
        run: |
           wget https://github.com/mapxn/enigma/releases/download/v0.0.1/mock.jar
           echo "TITLE_NAME=$(java -jar mock.jar)" >> $GITHUB_ENV
      - name: CommitFile
        id: step_two
        run: |
           git config --global user.name "mapxn"
           git config --global user.email "${{ secrets.EMAIL }}"
           git clone https://github.com/mapxn/enigma.git
           cd enigma
           git checkout gh-pages
           mv ../${{ env.TITLE_NAME }}.md ./_posts/
           git add -A
           git commit -m "Update engima"
           if [ $(($RANDOM%100+1)) -lt 45 ]; then git push https://mapxn:${{ secrets.GITHUB_TOKEN }}@github.com/mapxn/enigma.git gh-pages; fi
